name: Periodic Scraping

on:
  schedule:
    # 15分ごとに実行（UTCタイムゾーン）
    - cron: '*/15 * * * *'
  # 手動実行も可能に
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Run scraping
        run: |
          # アプリのエンドポイントに対してリクエストを送信
          curl -X GET "https://saunachecker.onrender.com/api/github-action-scraping"
          echo "Scraping job completed" 
