name: Periodic Scraping

on:
  schedule:
    # 15分ごとに実行（UTCタイムゾーン）
    - cron: '*/15 * * * *'
  # 手動実行も可能に
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Run scraping
        run: |
          echo "スクレイピングを開始します: $(date)"
          # タイムアウトを60秒に設定し、詳細な出力を有効化
          response=$(curl -X GET "https://saunachecker.onrender.com/api/github-action-scraping" -m 60 -v)
          echo "レスポンス: $response"
          echo "スクレイピングが完了しました: $(date)" 
